name: Deploy guides.lib.unb.ca

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  deploy:
    uses: unb-libraries/dockworker/.github/workflows/build-push-deploy-notify.yaml@6.x
    with:
      branch-env-map: '{"prod":"prod"}'
      build-themes: false
      deploy-branches: '["prod"]'
      image-name: 'ghcr.io/unb-libraries/guides.lib.unb.ca'
      k8s-deployment-name: 'guides-lib-unb-ca'
      push-branches: '["prod"]'
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GH_CONTAINER_REGISTRY_USER: ${{ secrets.GH_CONTAINER_REGISTRY_USER }}
      GH_CONTAINER_REGISTRY_TOKEN: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
